### ISSUE TITLE
Mongoose connection lost

### ISSUE THREAD

**Issue by gil0mendes** [StellarFw/stellar#29]
For some reason, or when we are developing the API locally the Internet connection can go down and the Mongoose will throw an error. This errors must be caught and the connection must be reestablished.

``` text
/Users/gil0mendes/Documents/projects/stellar/core/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:168
    var error = new Error(err && err.err || 'connection timeout');
                ^
Error: connection timeout
    at Db.<anonymous> (/Users/gil0mendes/Documents/projects/stellar/core/node_modules/mongoose/lib/drivers/node-mongodb-native/connection.js:168:17)
    at emitTwo (events.js:106:13)
    at Db.emit (events.js:191:7)
    at Server.listener (/Users/gil0mendes/Documents/projects/stellar/core/node_modules/mongodb/lib/db.js:1791:14)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Server.<anonymous> (/Users/gil0mendes/Documents/projects/stellar/core/node_modules/mongodb/lib/server.js:270:14)
    at Server.g (events.js:291:16)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at Pool.<anonymous> (/Users/gil0mendes/Documents/projects/stellar/core/node_modules/mongodb-core/lib/topologies/server.js:322:12)
    at emitOne (events.js:96:13)
    at Pool.emit (events.js:188:7)
    at Connection.<anonymous> (/Users/gil0mendes/Documents/projects/stellar/core/node_modules/mongodb-core/lib/connection/pool.js:260:12)
    at Connection.g (events.js:291:16)
    at emitTwo (events.js:106:13)
```

**Comment by gil0mendes** [comment]
This was fixed by implementing the new ORM system!
