### ISSUE TITLE
Catch erros on the ActionProcessor

### ISSUE THREAD

**Issue by gil0mendes** [StellarFw/stellar#55]
### Running System

- Stellar Version: `1.1.x`
- Node.js Version: `Node Independent`
- Operating System: `OS independent`

### Steps to Reproduce Your Error

Create an action with valid syntax but with a undefined variable on the `run` function.

### What is Expected?

- The server should respond with a error message with the HTTP status code `500`.
- On the console we should got and error message with the stack trace, but without breaking the Stellar instance.

### What is Actually Happening?

The server crash and we got the following error on the console:

```text
Repairs.js:24
    const query = actions.params.query
                  ^
ReferenceError: actions is not defined
    at Object.run (/Users/gil0mendes/Documents/projects/tecniphone/api/modules/private/actions/repair/searchForRepairs.js:24:19)
    at preProcessAction.error (/Users/gil0mendes/Documents/projects/stellar/core/src/satellites/actionProcessor.js:329:47)
    at /Users/gil0mendes/Documents/projects/stellar/core/node_modules/async/dist/async.js:3694:9
```

**Comment by gil0mendes** [comment]
This was already fixed by some previous commit. 😅
